"""
Moose settings for {{ project_name }} project.

Generated by 'moose-admin startproject' using Django {{ django_version }}.

For more information on this file, see

For the full list of settings and their values, see
"""

import os
import codecs
import locale
import logging
import logging.config
from os.path import join, normpath

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

import platform
IS_WINDOWS = True if platform.system()=="Windows" else False
IS_POSIX = not IS_WINDOWS

# dir settings
PROJECT_ROOT = os.getcwd()
def norm_porject_path(*args):
    return normpath(join(PROJECT_ROOT, *args))

TOOLS_DIR = norm_porject_path('..', 'tools')
DATA_DIR = norm_porject_path('..', 'data')
CONF_DIR = norm_porject_path('..', 'conf')
LOGS_DIR = norm_porject_path('..', 'logs')
APPS_DIR = norm_porject_path('apps')


template_app = norm_porject_path('core', 'app_template.py')

if not os.path.exists(DATA_DIR):
    os.makedirs(DATA_DIR)

if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)


# config settings
COMMON_CONF_FILE = norm_porject_path('conf', 'common.cfg')
CONF_GEN_SCRIPT_NAME = 'gen_template.py'
CONF_TEMPLATE_NAME = 'template.cfg'
CONF_IN_USING_NAME = 'config.cfg'

DEFAULT_TIMEOUT = 60

# base settings for all connection
CONNECTION_SETTINGS = {
    "timeout": 300,
    "interval": 300,
    "retry": 3
}

# azure settings
AZURE_SETTINGS = {
    "account": "crowdfile",
    "key": "LPKAQIkvntlpsZm+EBTB2JfjILpObuRfYzwhmBk31/ILoafSLzwkJaBQDhwcW4rpXks7UGi3+e2+1eCHHCn+SQ==",
    "endpoint_suffix": "core.chinacloudapi.cn",
    "workers": 4,
    "chunks": 8,
}

# database settings
MONGODB_SETTINGS = {
    "host": "crowdser.chinacloudapp.cn",
    "port": "38011",
    "user": "crowd_read",
    "password": "crowdread",
}

SQLSERVER_SETTINGS = {
    "host": "crowdser.chinacloudapp.cn",
    "port": "9280",
    "user": "sa",
    "password": "2015_zaixianSimple",
    "database": "CrowdDB",
    "charset": "UTF-8",
}

SMB_SETTINGS = {
    "host": "10.10.8.123",
    "port": 139, # 139 if using NetBIOS over tcp/ip, 445 if direct hosting over tcp/ip
    "username": "administrator",
    "password": "Shujutang18FF",
    "domain": "",   # workgroup, it is safe to leave it empty
    "client_name": "DATATANG",  # an arbitary ASCII string
    "server_name": "WIN-DJM4V2HB0T5",
    # NTLMv1 or NTLMv2 authentication will be used, guess to be True for WIN7, Vista
    "use_ntlm_v2": True,

    "reconnect_times": 3,
    "connect_timeout": 60,
    "echo_timeout": 30,
    "retrive_timeout": 120,
    "reconnect_interval": 300,
}

WEB_SETTINGS = {
    "username": "crowd_tech",
    "password": "2017_data@Tech",
}

BROWSER_SIMULATOR = "Firefox"   # Firefox, Chrome, Ie, Opera
COOKIE_PATH = os.path.join(TOOLS_DIR, 'cookie')

DECRYPT_SETTINGS = {
    "key_path": os.path.join(TOOLS_DIR, 'key'),
    "timeout": 60,
}

DOWNLOAD_SETTINGS = {
    "queue_buffer": 2500,
    "queue_timeout": 60,
    "download_timeout": 60,
}

# tools are assumed to be put at the dir named tools
TOOLS_SETTINGS = {
    
}

# email settings
MAIL_SETTINGS = {
    "smtp_server": "mail.datatang.com",
    "smtp_port": 25,
    "smtp_user": None,
    "smtp_pass": None,
    "sender": "tech@datatang.com"
}

NOTIFY_MAIL_SETTINGS = {
    "subject": "[automate] {title}",
    "content": "Task {title} you started before is finised now."
}

# logs settings
LOGGING_CONF_FILE = norm_porject_path('conf', 'logging.conf')
logging.config.fileConfig(LOGGING_CONF_FILE)
logger = logging.getLogger('root')

# others
EDITOR = "vim"
OFFLINE = None

DATALINK_TEMPLATE = 'http://bz.datatang.com/datalink?data={data_guid}&taskId={task_id}'
AZURE_FILELINK = 'http://crowdfile.blob.core.chinacloudapi.cn/{task_id}/{file_path}'

PREFERRED_PROJECT_NAME = u"%d第%d期图片标注任务"

RESERVED_FILES = [
    '.gitignore',
    CONF_GEN_SCRIPT_NAME,
    CONF_TEMPLATE_NAME,
    CONF_IN_USING_NAME,
    ]

